from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/emails/', views.get_emails, name='get_emails'),
    path('admin-dashboard/delete/<int:email_id>/', views.delete_email, name='delete_email'),
    path('admin-dashboard/delete-all/', views.delete_all_emails, name='delete_all_emails'),
    path('delete-all-emails-for-team/', views.delete_all_emails_for_team, name='delete_all_emails_for_team'),
    path('delete-team-email/<int:email_id>/', views.delete_team_email, name='delete_team_email'),
    path('delete-tl-email/<int:email_id>/', views.delete_tl_email, name='delete_tl_email'),
    path('admin-dashboard/assign-emails/', views.assign_emails_to_team, name='assign_emails_to_team'),
    path('admin-dashboard/emails/', views.get_emails, name='get_emails'),
    path('team-dashboard/', views.team_dashboard, name='team_dashboard'),
    path('team-dashboard-data/', views.team_dashboard_data, name='team_dashboard_data'),
    path('export-team-emails/', views.export_team_emails, name='export_team_emails'),
    path('admin-files-data/', views.admin_files_data, name='admin_files_data'),
    path('delete-file/<int:file_id>/', views.delete_file, name='delete_file'),
    path('admin-dashboard-data/', views.admin_dashboard_data, name='admin_dashboard_data'),
    path('delete-all-emails/', views.delete_all_emails, name='delete_all_emails'),
    path('delete-email/<int:email_id>/', views.delete_email, name='delete_email'),
    path('delete-emails-by-source/<int:file_id>/', views.delete_emails_by_source, name='delete_emails_by_source'),
    path('update-team-email-status/', views.update_team_email_status, name='update_team_email_status'),
    path('update-tl-email-status/', views.update_tl_email_status, name='update_tl_email_status'),
    path('tl-dashboard/', views.tl_dashboard, name='tl_dashboard'),
    path('tl-dashboard-data/', views.tl_dashboard_data, name='tl_dashboard_data'),
    path('assign-emails-to-team/', views.assign_emails_to_team, name='assign_emails_to_team'),
    path('get-emails/', views.get_emails, name='get_emails'),
    path('assign-emails-to-tls/', views.assign_emails_to_tls, name='assign_emails_to_tls'),
    path('export-tl-emails/', views.export_tl_emails, name='export_tl_emails'),
    path('import-tl-emails/', views.import_tl_emails, name='import_tl_emails'),
    path('delete-all-tl-emails/', views.delete_all_tl_emails, name='delete_all_tl_emails'),
    path('closed-emails/', views.closed_emails_page, name='closed_emails_page'),
    path('closed-emails-data/', views.closed_emails_data, name='closed_emails_data'),
    path('delete-closed-email/<int:email_id>/', views.delete_closed_email, name='delete_closed_email'),
    path('manager-closed-emails/', views.closed_emails_page, name='manager_closed_emails'),
    path('logout/', views.logout_view, name='logout'),
]