# Generated by Django 5.1.7 on 2025-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_id', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('two_fa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('two_fa_link', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_team', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('problem_reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('closure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('closure_requested_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emails',
                'managed': False,
            },
        ),
    ]
