# Generated by Django 5.2.4 on 2025-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
    ]
