# Generated by Django 5.2.4 on 2025-07-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_email_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='assigned_team',
        ),
        migrations.AddField(
            model_name='email',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team'),
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
    ]
