# Generated by Django 5.1.7 on 2025-07-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_email_assigned_team_email_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Team A', 'Team A'), ('Team B', 'Team B')], max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='email',
            table='emails',
        ),
        migrations.AddField(
            model_name='email',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='dashboard.file'),
        ),
    ]
