# Generated by Django 5.1.7 on 2025-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_file_email_code_alter_team_name_alter_email_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='source_file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
