# Generated by Django 5.1.7 on 2025-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_admin_email',
            field=models.BooleanField(default=True),
        ),
    ]
