# Generated by Django 5.2.4 on 2025-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_email_is_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('closed', 'closed')], default='working', max_length=20),
        ),
    ]
