# Generated by Django 5.1.7 on 2025-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Manager 1', 'Manager 1'), ('Manager 2', 'Manager 2')], max_length=100, unique=True),
        ),
    ]
