# Generated by Django 5.1.7 on 2025-07-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_admin_email',
        ),
    ]
