# Generated by Django 5.1.7 on 2025-07-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_email_is_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to='dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('hotmail', 'Hotmail'), ('yahoo', 'Yahoo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('tl', 'TL')], default='tl', max_length=20),
        ),
    ]
