# Generated by Django 5.1.7 on 2025-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_email_assigned_to_userprofile_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='dashboard_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tl', 'TL')], default='admin', max_length=20),
        ),
    ]
