# Generated by Django 5.1.7 on 2025-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_email_dashboard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='dashboard_type',
        ),
        migrations.AddField(
            model_name='email',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('admin_only', 'Admin Only'), ('manager_only', 'Manager Only'), ('tl_only', 'TL Only')], default='all', max_length=20),
        ),
    ]
