# Generated by Django 5.1.7 on 2025-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_email_dashboard_type_email_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='visibility',
        ),
        migrations.AddField(
            model_name='email',
            name='deleted_by',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tl', 'TL'), ('', 'Not Deleted')], default='', max_length=20),
        ),
    ]
