# Generated by Django 5.1.7 on 2025-07-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_email_visibility_email_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='deleted_by',
        ),
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('two_fa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('two_fa_link', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('working', 'working'), ('closed', 'closed')], default='working', max_length=20)),
                ('problem_reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('closure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('closure_requested_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file_id', models.IntegerField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_emails', to='dashboard.file')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
            options={
                'db_table': 'admin_emails',
            },
        ),
        migrations.CreateModel(
            name='ManagerEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('two_fa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('two_fa_link', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('working', 'working'), ('closed', 'closed')], default='working', max_length=20)),
                ('problem_reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('closure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('closure_requested_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manager_emails', to='dashboard.userprofile')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_emails', to='dashboard.file')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
            options={
                'db_table': 'manager_emails',
            },
        ),
        migrations.CreateModel(
            name='TLEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('two_fa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('two_fa_link', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('working', 'working'), ('closed', 'closed')], default='working', max_length=20)),
                ('problem_reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('closure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('closure_requested_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tl_emails', to='dashboard.userprofile')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_emails', to='dashboard.file')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
            options={
                'db_table': 'tl_emails',
            },
        ),
    ]
