# Generated by Django 5.2.4 on 2025-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_email_deleted_by_adminemail_manageremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='provider',
            new_name='tl_provider',
        ),
        migrations.AddField(
            model_name='manageremail',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
