# Generated by Django 5.1.7 on 2025-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_provider_userprofile_tl_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlemail',
            name='price',
        ),
        migrations.AddField(
            model_name='tlemail',
            name='new_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
