# Generated by Django 5.1.7 on 2025-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_tlemail_price_tlemail_new_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageremail',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('closed', 'closed'), ('pending_closed', 'Pending Closed')], default='working', max_length=20),
        ),
        migrations.AlterField(
            model_name='tlemail',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('closed', 'closed'), ('pending_closed', 'Pending Closed')], default='working', max_length=20),
        ),
    ]
