# Generated by Django 5.1.7 on 2025-07-29 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_manageremail_status_alter_tlemail_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('recovery_email', models.CharField(blank=True, max_length=255, null=True)),
                ('new_password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending_closed', max_length=20)),
                ('source_file_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_emails', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team')),
            ],
            options={
                'verbose_name': 'Closed Email',
                'verbose_name_plural': 'Closed Emails',
            },
        ),
    ]
